version: '2'

services:
  drupal:
    build: .
    container_name: drupal_wilmap
    volumes:
      - ./code/modules:/var/www/html/modules
      - ./code/themes:/var/www/html/themes
      - ./data/files:/var/www/html/sites/default/files
      - ./data/private:/var/www/private
    links:
      - mysql
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    container_name: mysql-wilmap
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wilmap
      MYSQL_DATABASE: wilmap_db
      MYSQL_PASSWORD: wilmap_root
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backup:/backup
